#!/bin/bash

set -e;

APP="$1"
APP_PORT=$(docker port d4d5f5b35856 5000 | sed 's/0.0.0.0://')
LOCAL_IP="172.17.42.1"

VARNISH_IMAGE="varnish/$APP"
VARNISH_DIR="$DOKKU_ROOT/.varnish"
VARNISH_PORT=8080

VOLUME_PROPERTY="$VARNISH_DIR/volume_$APP"
PORT_PROPERTY="$VARNISH_DIR/port_$APP"

# Check if an existing varnish volume exists
VARNISH_IMAGE_ID=$(docker images | grep "$VARNISH_IMAGE" | awk '{print $3}')
if [[ -n $VARNISH_IMAGE_ID ]]; then
  echo "-----> Checking status of Varnish"

  # Check if varnish container is installed
  IMAGE=$(docker images | grep "zenedith/varnish " | awk '{print $3}')
  if [[ -z $IMAGE ]]; then
    echo "Varnish image not found... Did you run 'dokku plugins-install' ?"
    exit 1
  fi

  echo    "       Found image varnish/$APP varnish instance"
  echo -n "       Checking status... "

  VARNISH_CONTAINER=$(docker ps | grep "$VARNISH_IMAGE" | awk '{print $1}')
  if [[ -n $VARNISH_CONTAINER ]]; then
    echo "ok."
  else
    echo "stopped."

    VOLUME="`cat $VOLUME_PROPERTY`:/opt/varnish"
    PORT="`cat $PORT_PROPERTY`"

    # Launch container
    echo -n "       Launching $VARNISH_IMAGE... "
    echo "COMMAND: docker run -e BACKEND_PORT_${APP_PORT}_TCP_ADDR=$LOCAL_IP -e BACKEND_ENV_PORT=$APP_PORT -v $VOLUME -p $VARNISH_PORT:$PORT -d $VARNISH_IMAGE /bin/run.sh"
    ID=$(docker run -e BACKEND_PORT_${APP_PORT}_TCP_ADDR=$LOCAL_IP -e BACKEND_ENV_PORT=$APP_PORT -v $VOLUME -p $VARNISH_PORT:$PORT -d $VARNISH_IMAGE /bin/run.sh)
    sleep 1
    echo "ok."
  fi
fi
